name: activatory
description: Test data generator for Dart ecosystem. Simplifies unit testing and Test-Driven Development.
version: 1.2.2
homepage: https://github.com/syberside/Activatory

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  uuid: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^5.0.3
  pedantic:  ^1.9.0
